# Generated by Django 4.1.3 on 2022-12-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_options', '0002_alter_page_options_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page_Options',
            new_name='Page_Option',
        ),
    ]
