# Generated by Django 4.1.3 on 2022-12-20 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_logo', models.ImageField(blank=True, default='page/logo.png', null=True, upload_to='page/')),
                ('title_image', models.ImageField(blank=True, default='page/title_image.png', null=True, upload_to='page/')),
                ('banner_image', models.ImageField(blank=True, default='page/banner.jpg', null=True, upload_to='page/')),
                ('team_image', models.ImageField(blank=True, default='page/team.jpg', null=True, upload_to='page/')),
                ('services_image', models.ImageField(blank=True, default='page/services.jpeg', null=True, upload_to='page/')),
                ('address_unit', models.IntegerField(blank=True, null=True)),
                ('address_street', models.TextField()),
                ('address_city', models.TextField()),
                ('address_province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NF', 'New Foundland'), ('NS', 'Nova Scotia'), ('NV', 'Nunavut'), ('NW', 'North West Territories'), ('ONT', 'Ontario'), ('PEI', 'Prince Endward Island'), ('QBC', 'Quebec'), ('SK', 'Saskatchewan'), ('YK', 'Yukon')], max_length=3)),
                ('phone_number_area_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Only numbers allowed', regex='^[0-9]*$'), django.core.validators.MinLengthValidator(3)])),
                ('phone_number_prefix', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Only numbers allowed', regex='^[0-9]*$'), django.core.validators.MinLengthValidator(3)])),
                ('phone_number_line', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Only numbers allowed', regex='^[0-9]*$'), django.core.validators.MinLengthValidator(4)])),
                ('contact_email', models.EmailField(max_length=254)),
                ('show_team', models.BooleanField(default=False)),
            ],
        ),
    ]
