# Generated by Django 4.1.3 on 2022-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_options', '0003_rename_page_options_page_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_option',
            name='address_unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
