# Generated by Django 4.1.3 on 2022-12-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_options', '0004_alter_page_option_address_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_option',
            name='address_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='page_option',
            name='address_street',
            field=models.CharField(max_length=50),
        ),
    ]
