# Generated by Django 4.1.3 on 2022-11-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='path',
            new_name='ImagePath',
        ),
    ]
