# Generated by Django 4.1.3 on 2022-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
