# Generated by Django 4.1.3 on 2022-11-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_path_service_imagepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ImagePath',
            new_name='image_path',
        ),
    ]
