# Generated by Django 4.1.3 on 2022-12-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
